Repository rancher/terraform-provider-rancher2, pull requests merged in 2019-08, with the labels that each got.

#52 Cluster and project logging data sources
  CHANGELOG.md
  rancher2/data_source_rancher2_cluster_logging.go
  rancher2/data_source_rancher2_cluster_logging_test.go
  rancher2/data_source_rancher2_cluster_role_template_binding.go
  rancher2/data_source_rancher2_cluster_role_template_binding_test.go
  rancher2/data_source_rancher2_project_logging.go
  rancher2/data_source_rancher2_project_logging_test.go
  rancher2/data_source_rancher2_project_role_template_binding.go
  rancher2/data_source_rancher2_project_role_template_binding_test.go
  rancher2/provider.go
  website/docs/d/clusterLogging.html.markdown
  website/docs/d/projectLogging.html.markdown
  website/docs/r/clusterLogging.html.markdown
  website/docs/r/projectLogging.html.markdown
  website/rancher2.erb
Labels: documentation, new-data-source, size/XL

#62 Added cluster and project scope support on rancher2_catalog resource and datasource
  CHANGELOG.md
  rancher2/config.go
  rancher2/data_source_rancher2_catalog.go
  rancher2/data_source_rancher2_catalog_test.go
  rancher2/import_rancher2_catalog.go
  rancher2/resource_rancher2_catalog.go
  rancher2/resource_rancher2_catalog_test.go
  rancher2/schema_catalog.go
  rancher2/structure_catalog.go
  rancher2/structure_catalog_test.go
  website/docs/d/catalog.html.markdown
  website/docs/r/catalog.html.markdown
Labels: documentation, enhancement, size/XXL

#75 Added rancher2_registry resource and datasource
  CHANGELOG.md
  rancher2/config.go
  rancher2/data_source_rancher2_registry.go
  rancher2/data_source_rancher2_registry_test.go
  rancher2/import_rancher2_registry.go
  rancher2/provider.go
  rancher2/resource_rancher2_registry.go
  rancher2/resource_rancher2_registry_test.go
  rancher2/schema_registry.go
  rancher2/structure_registry.go
  rancher2/structure_registry_test.go
  rancher2/util.go
  website/docs/d/registry.html.markdown
  website/docs/r/registry.html.markdown
  website/rancher2.erb
Labels: documentation, enhancement, new-data-source, new-resource, size/XXL

#76 Added custom_ca argument on etcd s3_backup_config on rancher2_cluster and rancher2_etcd_backup resources
  CHANGELOG.md
  go.mod
  go.sum
  rancher2/resource_rancher2_etcd_backup.go
  rancher2/schema_cluster_rke_config_services.go
  rancher2/structure_cluster_rke_config_services.go
  rancher2/structure_cluster_rke_config_services_test.go
  rancher2/structure_etcd_backup.go
  rancher2/structure_etcd_backup_test.go
  scripts/start_testacc.sh
  vendor/github.com/rancher/types/client/management/v3/zz_generated_cert_expiration.go
  vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster.go
  vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster_status.go
  vendor/github.com/rancher/types/client/management/v3/zz_generated_node_driver_status.go
  vendor/github.com/rancher/types/client/management/v3/zz_generated_pagerduty_config.go
  vendor/github.com/rancher/types/client/management/v3/zz_generated_s3backup_config.go
  vendor/github.com/rancher/types/client/management/v3/zz_generated_slack_config.go
  vendor/github.com/rancher/types/client/management/v3/zz_generated_webhook_config.go
  vendor/github.com/rancher/types/client/management/v3/zz_generated_wechat_config.go
  vendor/modules.txt
  website/docs/r/cluster.html.markdown
  website/docs/r/etcdBackup.html.markdown
Labels: dependencies, documentation, enhancement, size/L

#81 Set default value to engine_install_url argument on rancher2_node_template resource
  CHANGELOG.md
  rancher2/schema_node_template.go
  website/docs/r/nodeTemplate.html.markdown
Labels: documentation, enhancement, size/XS

#67 Updated provider config validation to enable bootstrap and resource creation at same run
  CHANGELOG.md
  rancher2/config.go
  rancher2/provider.go
  rancher2/resource_rancher2_bootstrap_test.go
  website/docs/index.html.markdown
  website/docs/r/bootstrap.html.markdown
Labels: documentation, enhancement, size/M

#66 Added enable_cluster_monitoring and enable_project_monitoring to rancher2 cluster and project
  CHANGELOG.md
  rancher2/data_source_rancher2_cluster.go
  rancher2/data_source_rancher2_project.go
  rancher2/resource_rancher2_cluster.go
  rancher2/resource_rancher2_project.go
  rancher2/schema_cluster.go
  rancher2/schema_project.go
  rancher2/structure_cluster.go
  rancher2/structure_cluster_test.go
  rancher2/structure_project.go
  rancher2/structure_project_test.go
  website/docs/d/cluster.html.markdown
  website/docs/d/project.html.markdown
  website/docs/r/cluster.html.markdown
  website/docs/r/project.html.markdown
Labels: documentation, enhancement, size/M

#82 Added container_resource_limit and pod_security_policy_template_id arguments
  CHANGELOG.md
  rancher2/data_source_rancher2_namespace.go
  rancher2/data_source_rancher2_project.go
  rancher2/schema_container_resource_limit.go
  rancher2/schema_namespace.go
  rancher2/schema_project.go
  rancher2/structure_namespace.go
  rancher2/structure_namespace_test.go
  rancher2/structure_project.go
  rancher2/structure_project_test.go
  website/docs/d/namespace.html.markdown
  website/docs/d/project.html.markdown
  website/docs/r/namespace.html.markdown
  website/docs/r/project.html.markdown
Labels: documentation, size/XL

#73 Added wait_for_cluster argument on rancher2_namespace and rancher2_project resources
  CHANGELOG.md
  rancher2/resource_rancher2_namespace.go
  rancher2/resource_rancher2_namespace_test.go
  rancher2/resource_rancher2_project.go
  rancher2/resource_rancher2_project_test.go
  rancher2/schema_namespace.go
  rancher2/schema_project.go
  website/docs/r/namespace.html.markdown
  website/docs/r/project.html.markdown
Labels: documentation, enhancement, size/M

#88 Removed docker_version argument from rancher2_node_template resource
  CHANGELOG.md
  rancher2/resource_rancher2_node_template.go
  rancher2/schema_node_template.go
  rancher2/structure_node_template.go
  website/docs/r/nodeTemplate.html.markdown
Labels: documentation, size/XS

#95 Fix auth issue when using access_key and secret_key
  CHANGELOG.md
  rancher2/00_provider_test.go
  rancher2/config.go
  rancher2/provider.go
Labels: size/S

#97 Bump azure ubuntu image
  rancher2/schema_node_template_azure.go
  website/docs/r/nodeTemplate.html.markdown
Labels: documentation, size/XS

#99 Fix container_resource_limit argument update issue
  CHANGELOG.md
  rancher2/resource_rancher2_namespace.go
  rancher2/resource_rancher2_namespace_test.go
  rancher2/resource_rancher2_project.go
  rancher2/resource_rancher2_project_test.go
  website/docs/r/namespace.html.markdown
  website/docs/r/project.html.markdown
Labels: documentation, size/M

#101 Added folder argument on s3_backup_config
  CHANGELOG.md
  go.mod
  go.sum
  rancher2/resource_rancher2_cluster_role_template_binding_test.go
  rancher2/resource_rancher2_etcd_backup_test.go
  rancher2/schema_cluster_rke_config_services.go
  rancher2/schema_etcd_backup.go
  rancher2/structure_cluster_rke_config_services.go
  rancher2/structure_cluster_rke_config_services_test.go
  rancher2/structure_etcd_backup_test.go
  scripts/start_testacc.sh
  vendor/github.com/rancher/types/client/management/v3/zz_generated_s3backup_config.go
  vendor/modules.txt
  website/docs/r/cluster.html.markdown
  website/docs/r/etcdBackup.html.markdown
Labels: dependencies, documentation, enhancement, size/M

#102 New datasource for node_template
  CHANGELOG.md
  rancher2/data_source_rancher2_node_template.go
  rancher2/data_source_rancher2_node_template_test.go
  rancher2/provider.go
  website/docs/d/cluster.html.markdown
  website/docs/d/clusterDriver.html.markdown
  website/docs/d/clusterLogging.html.markdown
  website/docs/d/etcdBackup.html.markdown
  website/docs/d/namespace.html.markdown
  website/docs/d/nodeDriver.html.markdown
  website/docs/d/nodePool.html.markdown
  website/docs/d/nodeTemplate.html.markdown
  website/docs/d/projectLogging.html.markdown
  website/rancher2.erb
Labels: documentation, enhancement, new-data-source, size/XL

#103 Fix: set access_key and secret_key arguments as optional on s3_backup_config
  CHANGELOG.md
  rancher2/schema_cluster_rke_config_services.go
  rancher2/structure_cluster_rke_config_services.go
  website/docs/r/cluster.html.markdown
  website/docs/r/etcdBackup.html.markdown
Labels: documentation, size/XS

#114 Enhancements on eks_config
  CHANGELOG.md
  rancher2/schema_cluster_eks_config.go
  rancher2/structure_cluster_eks_config.go
  rancher2/structure_cluster_eks_config_test.go
  website/docs/r/cluster.html.markdown
Labels: documentation, enhancement, size/XS

#115 Fix: don't delete builtin cluster nor node drivers from rancher on tf destroy
  rancher2/resource_rancher2_cluster_driver.go
  rancher2/resource_rancher2_node_driver.go
Labels: bug, size/M

#117 Fix: wrong updates on sensitive arguments on cluster and project logging resources
  CHANGELOG.md
  rancher2/structure_cluster_logging.go
  rancher2/structure_logging_elasticsearch_config.go
  rancher2/structure_logging_elasticsearch_config_test.go
  rancher2/structure_logging_fluentd_config.go
  rancher2/structure_logging_fluentd_config_test.go
  rancher2/structure_logging_kafka_config.go
  rancher2/structure_logging_kafka_config_test.go
  rancher2/structure_logging_splunk_config.go
  rancher2/structure_logging_splunk_config_test.go
  rancher2/structure_logging_syslog_config.go
  rancher2/structure_logging_syslog_config_test.go
  rancher2/structure_project_logging.go
Labels: size/L

#121 quantity argument on rancher2_node_pool resource should be >= 1
  CHANGELOG.md
  rancher2/schema_node_pool.go
  website/docs/r/nodePool.html.markdown
Labels: documentation, size/XS
