Repository rancher/terraform-provider-rancher2, pull requests merged in 2019-12, with the labels that each got.

#199 Add Not Null (API states has-value) to Alerts/Metric
  rancher2/schema_alert_rule.go
  website/docs/r/clusterAlertRule.html.markdown
  website/docs/r/projectAlertRule.html.markdown
Labels: documentation, size/XS

#196 Added GetRancherVersion function to provider config
  CHANGELOG.md
  rancher2/config.go
Labels: size/S

#197 Updated vsphere_config argument schema on rancher2_node_template resource
  CHANGELOG.md
  rancher2/schema_node_template.go
  rancher2/schema_node_template_vsphere.go
  rancher2/structure_node_template_vsphere.go
  scripts/start_testacc.sh
  website/docs/r/nodeTemplate.html.markdown
Labels: documentation, enhancement, size/L

#202 Add Send Resolved to Notifier Resource
  rancher2/resource_rancher2_notifier.go
  rancher2/resource_rancher2_notifier_test.go
  rancher2/schema_notifier.go
  rancher2/structure_notifier.go
  website/docs/d/notifier.html.markdown
  website/docs/r/notifier.html.markdown
Labels: documentation, size/S

#205 Fixed Typo
  website/docs/index.html.markdown
Labels: documentation, size/XS

#203 Added refresh argument on rancher2_catalog resources
  CHANGELOG.md
  rancher2/config.go
  rancher2/resource_rancher2_catalog.go
  rancher2/schema_catalog.go
  website/docs/r/catalog.html.markdown
Labels: documentation, enhancement, size/M

#204 Added name and is_external arguments to rancher2_user datasource
  CHANGELOG.md
  rancher2/data_source_rancher2_user.go
  website/docs/d/user.html.markdown
Labels: documentation, enhancement, size/S

#208 Added delete_not_ready_after_secs and node_taints arguments to node_pool resource
  CHANGELOG.md
  rancher2/data_source_rancher2_node_pool.go
  rancher2/resource_rancher2_node_pool.go
  rancher2/resource_rancher2_node_pool_test.go
  rancher2/schema_node_pool.go
  rancher2/schema_taint.go
  rancher2/structure_node_pool.go
  rancher2/structure_node_pool_test.go
  rancher2/structure_taint.go
  rancher2/structure_taint_test.go
  website/docs/d/nodePool.html.markdown
  website/docs/r/nodePool.html.markdown
Labels: documentation, enhancement, size/XL

#215 Restored rancher2_cluster_sync doc reference on website/rancher2.erb file
  website/rancher2.erb
Labels: documentation, size/XS
