Repository rancher/terraform-provider-rancher2, pull requests merged in 2019-06, with the labels that each got.

#21 Fix on cluster resource for rke_config argument openstack cloud_provider
  go.mod
  go.sum
  rancher2/schema_cluster_rke_config_cloud_provider_openstack.go
  rancher2/structure_cluster_rke_config_cloud_provider_openstack.go
  rancher2/structure_cluster_rke_config_cloud_provider_openstack_test.go
  vendor/github.com/rancher/norman/httperror/error.go
  vendor/github.com/rancher/types/client/management/v3/zz_generated_cloudflare_provider_config.go
  vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster_test_input.go
  vendor/github.com/rancher/types/client/management/v3/zz_generated_load_balancer_openstack_opts.go
  vendor/github.com/rancher/types/client/management/v3/zz_generated_project_role_template_binding.go
  vendor/github.com/rancher/types/client/management/v3/zz_generated_project_test_input.go
  vendor/modules.txt
  website/docs/r/cluster.html.markdown
Labels: bug, dependencies, documentation, size/M

#10 Add data source for Rancher 2 projects
  rancher2/00_provider_test.go
  rancher2/data_source_rancher2_project.go
  rancher2/data_source_rancher2_project_test.go
  rancher2/provider.go
  website/docs/d/project.html.markdown
  website/rancher2.erb
Labels: documentation, enhancement, new-data-source, size/L

#29 Updated rancher2_etcd_backup resource and acceptance tests to work on rancher v2.2.4
  CHANGELOG.md
  rancher2/resource_rancher2_etcd_backup.go
  rancher2/resource_rancher2_etcd_backup_test.go
  rancher2/schema_etcd_backup.go
  scripts/start_testacc.sh
  website/docs/r/etcdBackup.html.markdown
Labels: documentation, enhancement, size/M

#28 Feats and fixes on rancher2_cluster resource and docs
  rancher2/resource_rancher2_cluster.go
  rancher2/schema_cluster.go
  rancher2/schema_cluster_rke_config.go
  rancher2/schema_cluster_rke_config_services.go
  rancher2/structure_cluster.go
  rancher2/structure_cluster_test.go
  website/docs/r/cluster.html.markdown
  website/docs/r/nodeTemplate.html.markdown
Labels: documentation, enhancement, size/L

#35 Fix: index out of range on rancher2_cluster resource rke_config_cloud_provider_vsphere
  CHANGELOG.md
  rancher2/structure_cluster_rke_config_cloud_provider_vsphere.go
Labels: size/XS

#32 Updated certificate argument on rancher2_auth_config_openldap and rancher2_auth_config_freeipa resources
  rancher2/structure_auth_config_freeipa_test.go
  rancher2/structure_auth_config_ldap.go
  rancher2/structure_auth_config_ldap_test.go
  rancher2/structure_auth_config_openldap_test.go
  rancher2/util.go
  website/docs/r/authConfigFreeIpa.html.markdown
  website/docs/r/authConfigOpenLdap.html.markdown
Labels: bug, documentation, size/S

#39 Added scheduler argument to services-rke_config argument on rancher2_cluster resource
  CHANGELOG.md
  rancher2/schema_cluster_rke_config_services.go
  rancher2/structure_cluster_rke_config_services.go
  rancher2/structure_cluster_rke_config_services_test.go
  website/docs/r/cluster.html.markdown
Labels: documentation, size/M
