Repository rancher/terraform-provider-rancher2, pull requests merged in 2019-11, with the labels that each got.

#173 Add azure managed disk support on rancher2_node_template resource
  CHANGELOG.md
  rancher2/schema_node_template_azure.go
  rancher2/structure_node_template_azure.go
  website/docs/r/nodeTemplate.html.markdown
Labels: documentation, enhancement, size/M

#174 Add desired nodes support on eks_config argument on rancher2_cluster resource
  CHANGELOG.md
  rancher2/schema_cluster_eks_config.go
  rancher2/structure_cluster_eks_config.go
  rancher2/structure_cluster_eks_config_test.go
  website/docs/r/cluster.html.markdown
Labels: documentation, enhancement, size/XS

#175 Fixes on rancher2_namespace and rancher2_project resources
  CHANGELOG.md
  rancher2/resource_rancher2_project.go
  rancher2/schema_container_resource_limit.go
  rancher2/schema_namespace.go
  rancher2/structure_namespace.go
  rancher2/structure_project.go
  website/docs/r/namespace.html.markdown
Labels: bug, documentation, size/S

#179 Fix rancher2_app update issue on Rancher v2.3.2
  CHANGELOG.md
  rancher2/data_source_rancher2_app_test.go
  rancher2/data_source_rancher2_multi_cluster_app_test.go
  rancher2/resource_rancher2_app.go
  rancher2/resource_rancher2_app_test.go
  rancher2/resource_rancher2_multi_cluster_app_test.go
  scripts/gotestacc.sh
  scripts/start_testacc.sh
Labels: bug, documentation, enhancement, size/S

#190 Remove merge artifact from cluster docs.
  website/docs/r/cluster.html.markdown
Labels: documentation, size/XS

#191 Fix typo in `manifests`
  website/docs/r/cluster.html.markdown
Labels: documentation, size/XS

#178 New rancher2_token resource
  CHANGELOG.md
  rancher2/provider.go
  rancher2/resource_rancher2_token.go
  rancher2/resource_rancher2_token_test.go
  rancher2/schema_token.go
  rancher2/structure_token.go
  rancher2/structure_token_test.go
  website/docs/r/token.html.markdown
  website/rancher2.erb
Labels: documentation, new-resource, size/XL

#186 Updated rancher2_etcd_backup documentation
  CHANGELOG.md
  website/docs/r/etcdBackup.html.markdown
Labels: documentation, size/XS
