Repository rancher/terraform-provider-rancher2, pull requests merged in 2019-07, with the labels that each got.

#44 Make AWS session token in EKS config sensitive
  rancher2/schema_cluster_eks_config.go
Labels: size/XS

#46 Fixes
  CHANGELOG.md
  rancher2/util.go
  website/docs/r/cluster.html.markdown
Labels: documentation, size/XS

#57 Support Rancher2 bootstrap behind corporate proxy
  rancher2/util.go
Labels: size/XS

#55 optional arguments eks_config argument on rancher2_cluster resource
  CHANGELOG.md
  rancher2/schema_cluster_eks_config.go
  website/docs/r/cluster.html.markdown
Labels: documentation, size/M

#56 required argument on `aks_config` argument on `rancher2_cluster` resource
  CHANGELOG.md
  rancher2/schema_cluster_aks_config.go
  website/docs/r/cluster.html.markdown
Labels: documentation, size/XS

#48 Cloud credential data source
  CHANGELOG.md
  rancher2/data_source_rancher2_cloud_credential.go
  rancher2/data_source_rancher2_cloud_credential_test.go
  rancher2/provider.go
  website/docs/d/cloudCredential.html.markdown
  website/rancher2.erb
Labels: documentation, size/L

#49 Catalog data source
  CHANGELOG.md
  rancher2/data_source_rancher2_catalog.go
  rancher2/data_source_rancher2_catalog_test.go
  rancher2/provider.go
  website/docs/d/catalog.html.markdown
  website/rancher2.erb
Labels: documentation, size/M

#54 Node pool data source
  CHANGELOG.md
  rancher2/data_source_rancher2_node_pool.go
  rancher2/data_source_rancher2_node_pool_test.go
  rancher2/provider.go
  rancher2/resource_rancher2_node_pool_test.go
  website/docs/d/nodePool.html.markdown
  website/docs/r/nodePool.html.markdown
  website/rancher2.erb
Labels: documentation, size/L

#58 Namespace data source
  CHANGELOG.md
  rancher2/data_source_rancher2_namespace.go
  rancher2/data_source_rancher2_namespace_test.go
  rancher2/provider.go
  website/docs/d/namespace.html.markdown
  website/rancher2.erb
Labels: documentation, size/L

#59 Etc Backup data source
  CHANGELOG.md
  rancher2/data_source_rancher2_etcd_backup.go
  rancher2/data_source_rancher2_etcd_backup_test.go
  rancher2/provider.go
  website/docs/d/etcdBackup.html.markdown
  website/rancher2.erb
Labels: documentation, size/L

#60 Cluster data source
  CHANGELOG.md
  rancher2/data_source_rancher2_cluster.go
  rancher2/data_source_rancher2_cluster_test.go
  rancher2/provider.go
  website/docs/d/cluster.html.markdown
  website/rancher2.erb
Labels: documentation, size/L

#61 User and global_role_binding resources and data sources
  CHANGELOG.md
  rancher2/config.go
  rancher2/data_source_rancher2_global_role_binding.go
  rancher2/data_source_rancher2_global_role_binding_test.go
  rancher2/data_source_rancher2_user.go
  rancher2/data_source_rancher2_user_test.go
  rancher2/import_rancher2_global_role_binding.go
  rancher2/import_rancher2_user.go
  rancher2/provider.go
  rancher2/resource_rancher2_global_role_binding.go
  rancher2/resource_rancher2_global_role_binding_test.go
  rancher2/resource_rancher2_user.go
  rancher2/resource_rancher2_user_test.go
  rancher2/schema_global_role_binding.go
  rancher2/schema_user.go
  rancher2/structure_global_role_binding.go
  rancher2/structure_global_role_binding_test.go
  rancher2/structure_user.go
  rancher2/structure_user_test.go
  website/docs/d/globalRole.html.markdown
  website/docs/d/user.html.markdown
  website/docs/r/globalRole.html.markdown
  website/docs/r/user.html.markdown
  website/rancher2.erb
Labels: documentation, size/XXL

#51 Cluster and project role template binding data sources
  CHANGELOG.md
  rancher2/data_source_cluster_role_template_binding.go
  rancher2/data_source_cluster_role_template_binding_test.go
  rancher2/data_source_project_role_template_binding.go
  rancher2/data_source_project_role_template_binding_test.go
  rancher2/provider.go
  website/docs/d/clusterRole.html.markdown
  website/docs/d/projectRole.html.markdown
  website/rancher2.erb
Labels: documentation, size/XL

#53 Cluster and node driver data sources
  CHANGELOG.md
  rancher2/data_source_rancher2_cluster_driver.go
  rancher2/data_source_rancher2_cluster_driver_test.go
  rancher2/data_source_rancher2_node_driver.go
  rancher2/data_source_rancher2_node_driver_test.go
  rancher2/provider.go
  website/docs/d/clusterDriver.html.markdown
  website/docs/d/nodeDriver.html.markdown
  website/rancher2.erb
Labels: documentation, size/XL

#78 website/cluster: Fix an attribute error
  website/docs/r/cluster.html.markdown
Labels: documentation, size/XS

#80 Fix the delete of a cluster when we don't have full read permission
  rancher2/resource_rancher2_cluster.go
  rancher2/util.go
Labels: bug, size/XS
