Repository rancher/terraform-provider-rancher2, pull requests merged in 2019-09, with the labels that each got.

#122 Fix: crash `rancher2_cluster` datasource if `enableNetworkPolicy` doesn't exist
  CHANGELOG.md
  rancher2/structure_cluster.go
Labels: bug, crash, size/XS

#124 Added rancher2_certificate and rancher2_secret datasource and resource
  CHANGELOG.md
  rancher2/config.go
  rancher2/data_source_rancher2_certificate.go
  rancher2/data_source_rancher2_certificate_test.go
  rancher2/data_source_rancher2_secret.go
  rancher2/data_source_rancher2_secret_test.go
  rancher2/import_rancher2_secret.go
  rancher2/provider.go
  rancher2/resource_rancher2_certificate.go
  rancher2/resource_rancher2_certificate_test.go
  rancher2/resource_rancher2_secret.go
  rancher2/resource_rancher2_secret_test.go
  rancher2/schema_certificate.go
  rancher2/schema_secret.go
  rancher2/structure_certificate.go
  rancher2/structure_certificate_test.go
  rancher2/structure_secret.go
  rancher2/structure_secret_test.go
  website/docs/d/certificate.html.markdown
  website/docs/d/secret.html.markdown
  website/docs/r/certificate.html.markdown
  website/docs/r/secret.html.markdown
  website/rancher2.erb
Labels: documentation, new-data-source, new-resource, size/XXL

#125 Added rancher2_app datasource and resource
  .travis.yml
  CHANGELOG.md
  go.mod
  go.sum
  rancher2/data_source_rancher2_app.go
  rancher2/data_source_rancher2_app_test.go
  rancher2/import_rancher2_app.go
  rancher2/provider.go
  rancher2/resource_rancher2_app.go
  rancher2/resource_rancher2_app_test.go
  rancher2/schema_app.go
  rancher2/structure_app.go
  rancher2/structure_app_test.go
  rancher2/util.go
  vendor/github.com/hashicorp/go-version/.travis.yml
  vendor/github.com/hashicorp/go-version/version.go
  vendor/modules.txt
  website/docs/d/app.html.markdown
  website/docs/r/app.html.markdown
  website/rancher2.erb
Labels: dependencies, documentation, new-data-source, new-resource, size/XXL

#128 Added rancher2_multi_cluster_app datasource and resource
  CHANGELOG.md
  rancher2/data_source_rancher2_multi_cluster_app.go
  rancher2/data_source_rancher2_multi_cluster_app_test.go
  rancher2/import_rancher2_multi_cluster_app.go
  rancher2/provider.go
  rancher2/resource_rancher2_multi_cluster_app.go
  rancher2/resource_rancher2_multi_cluster_app_test.go
  rancher2/schema_answer.go
  rancher2/schema_member.go
  rancher2/schema_multi_cluster_app.go
  rancher2/schema_target.go
  rancher2/schema_upgrade_strategy.go
  rancher2/structure_answer.go
  rancher2/structure_answer_test.go
  rancher2/structure_app.go
  rancher2/structure_member.go
  rancher2/structure_member_test.go
  rancher2/structure_multi_cluster_app.go
  rancher2/structure_multi_cluster_app_test.go
  rancher2/structure_target.go
  rancher2/structure_target_test.go
  rancher2/structure_upgrade_strategy.go
  rancher2/structure_upgrade_strategy_test.go
  website/docs/d/multiClusterApp.html.markdown
  website/docs/r/multiClusterApp.html.markdown
  website/rancher2.erb
Labels: documentation, new-data-source, new-resource, size/XXL

#130 Added rancher2_role_template data source and resource
  CHANGELOG.md
  rancher2/data_source_rancher2_role_template.go
  rancher2/data_source_rancher2_role_template_test.go
  rancher2/import_rancher2_role_template.go
  rancher2/provider.go
  rancher2/resource_rancher2_role_template.go
  rancher2/resource_rancher2_role_template_test.go
  rancher2/schema_policy_rule.go
  rancher2/schema_role_template.go
  rancher2/structure_policy_rule.go
  rancher2/structure_policy_rule_test.go
  rancher2/structure_role_template.go
  rancher2/structure_role_template_test.go
  website/docs/d/roleTemplate.html.markdown
  website/docs/r/roleTemplate.html.markdown
  website/rancher2.erb
Labels: documentation, new-data-source, new-resource, size/XXL

#131 Added rancher2_cluster_sync resource
  CHANGELOG.md
  rancher2/config.go
  rancher2/provider.go
  rancher2/resource_rancher2_cluster_sync.go
  rancher2/resource_rancher2_namespace.go
  rancher2/resource_rancher2_project.go
  rancher2/schema_cluster_sync.go
  website/docs/r/clusterSync.html.markdown
  website/rancher2.erb
Labels: documentation, new-resource, size/L

#132 Fix rancher2_app and rancher_multi_cluster_app to consistent manage external_id and template_version_id
  CHANGELOG.md
  rancher2/data_source_rancher2_multi_cluster_app.go
  rancher2/resource_rancher2_multi_cluster_app.go
  rancher2/structure_app.go
  rancher2/structure_app_test.go
  rancher2/structure_multi_cluster_app.go
  rancher2/structure_multi_cluster_app_test.go
  website/docs/r/app.html.markdown
  website/docs/r/multiClusterApp.html.markdown
Labels: documentation, size/L

#135 Fix: Allow AKS monitoring to be disabled
  rancher2/schema_cluster_aks_config.go
  rancher2/structure_cluster_aks_config.go
  rancher2/structure_cluster_aks_config_test.go
Labels: size/XS

#129 Add missing url path for rancher_url
  website/docs/r/authConfigAzureAD.html.markdown
Labels: documentation, size/XS

#138 Fix value_yaml multiline argument as base64 encoded
  CHANGELOG.md
  rancher2/resource_rancher2_app.go
  rancher2/schema_app.go
  rancher2/structure_app.go
  rancher2/structure_app_test.go
  website/docs/d/app.html.markdown
  website/docs/r/app.html.markdown
Labels: bug, documentation, size/S

#133 fix capitalization/spelling/grammar/etc in docs
  rancher2/schema_cluster_rke_config_dns.go
  website/docs/d/cluster.html.markdown
  website/docs/d/clusterDriver.html.markdown
  website/docs/d/nodePool.html.markdown
  website/docs/d/nodeTemplate.html.markdown
  website/docs/d/registry.html.markdown
  website/docs/d/user.html.markdown
  website/docs/index.html.markdown
  website/docs/r/app.html.markdown
  website/docs/r/authConfigADFS.html.markdown
  website/docs/r/authConfigActiveDirectory.html.markdown
  website/docs/r/authConfigAzureAD.html.markdown
  website/docs/r/authConfigFreeIpa.html.markdown
  website/docs/r/authConfigGithub.html.markdown
  website/docs/r/authConfigOpenLdap.html.markdown
  website/docs/r/authConfigPing.html.markdown
  website/docs/r/bootstrap.html.markdown
  website/docs/r/catalog.html.markdown
  website/docs/r/certificate.html.markdown
  website/docs/r/cloudCredential.html.markdown
  website/docs/r/cluster.html.markdown
  website/docs/r/clusterDriver.html.markdown
  website/docs/r/clusterLogging.html.markdown
  website/docs/r/clusterRole.html.markdown
  website/docs/r/etcdBackup.html.markdown
  website/docs/r/globalRole.html.markdown
  website/docs/r/multiClusterApp.html.markdown
  website/docs/r/namespace.html.markdown
  website/docs/r/nodeDriver.html.markdown
  website/docs/r/nodePool.html.markdown
  website/docs/r/nodeTemplate.html.markdown
  website/docs/r/project.html.markdown
  website/docs/r/projectLogging.html.markdown
  website/docs/r/projectRole.html.markdown
  website/docs/r/registry.html.markdown
  website/docs/r/roleTemplate.html.markdown
  website/docs/r/secret.html.markdown
  website/docs/r/setting.html.markdown
  website/docs/r/user.html.markdown
Labels: documentation, size/XL
