Repository rancher/terraform-provider-rancher2, pull requests merged in 2019-10, with the labels that each got.

#141 Added rancher2_notifier datasource and resource
  CHANGELOG.md
  rancher2/data_source_rancher2_notifier.go
  rancher2/data_source_rancher2_notifier_test.go
  rancher2/import_rancher2_notifier.go
  rancher2/provider.go
  rancher2/resource_rancher2_notifier.go
  rancher2/resource_rancher2_notifier_test.go
  rancher2/schema_notifier.go
  rancher2/schema_notifier_pagerduty_config.go
  rancher2/schema_notifier_slack_config.go
  rancher2/schema_notifier_smtp_config.go
  rancher2/schema_notifier_webhook_config.go
  rancher2/schema_notifier_wechat_config.go
  rancher2/structure_notifier.go
  rancher2/structure_notifier_pagerduty_config.go
  rancher2/structure_notifier_pagerduty_config_test.go
  rancher2/structure_notifier_slack_config.go
  rancher2/structure_notifier_slack_config_test.go
  rancher2/structure_notifier_smtp_config.go
  rancher2/structure_notifier_smtp_config_test.go
  rancher2/structure_notifier_webhook_config.go
  rancher2/structure_notifier_webhook_config_test.go
  rancher2/structure_notifier_wechat_config.go
  rancher2/structure_notifier_wechat_config_test.go
  rancher2/structure_notifier_z_test.go
  website/docs/d/notifier.html.markdown
  website/docs/r/notifier.html.markdown
  website/rancher2.erb
Labels: documentation, new-data-source, new-resource, size/XXL

#143 Added rancher2_auth_config_keycloak and rancher2_auth_config_okta resources
  CHANGELOG.md
  rancher2/config.go
  rancher2/provider.go
  rancher2/resource_rancher2_auth_config_keycloak.go
  rancher2/resource_rancher2_auth_config_keycloak_test.go
  rancher2/resource_rancher2_auth_config_okta.go
  rancher2/resource_rancher2_auth_config_okta_test.go
  rancher2/schema_auth_config_keycloak.go
  rancher2/schema_auth_config_okta.go
  rancher2/structure_auth_config_keycloak.go
  rancher2/structure_auth_config_keycloak_test.go
  rancher2/structure_auth_config_okta.go
  rancher2/structure_auth_config_okta_test.go
  website/docs/r/authConfigKeyCloak.html.markdown
  website/docs/r/authConfigOKTA.html.markdown
  website/rancher2.erb
Labels: documentation, new-resource, size/XXL

#144 Fix: removed limited values for default_pod_security_policy_template_id argument on rancher2_cluster resource
  CHANGELOG.md
  rancher2/schema_cluster.go
  website/docs/d/cluster.html.markdown
  website/docs/r/cluster.html.markdown
Labels: bug, documentation, size/XS

#145 Added argument to define monitoring config for rancher2_cluster and rancher2_project
  CHANGELOG.md
  rancher2/data_source_rancher2_cluster.go
  rancher2/import_rancher2_project.go
  rancher2/resource_rancher2_cluster.go
  rancher2/resource_rancher2_project.go
  rancher2/schema_cluster.go
  rancher2/schema_monitoring_input.go
  rancher2/schema_project.go
  rancher2/structure_cluster.go
  rancher2/structure_cluster_test.go
  rancher2/structure_monitoring_input.go
  rancher2/structure_monitoring_input_test.go
  rancher2/structure_project.go
  rancher2/structure_project_test.go
  website/docs/d/cluster.html.markdown
  website/docs/r/cluster.html.markdown
  website/docs/r/project.html.markdown
Labels: documentation, size/XL

#150 Added rancher2_alert_group and rancher2_alert_rule datasource and resource
  CHANGELOG.md
  rancher2/config.go
  rancher2/data_source_rancher2_cluster_alert_group.go
  rancher2/data_source_rancher2_cluster_alert_group_test.go
  rancher2/data_source_rancher2_cluster_alert_rule.go
  rancher2/data_source_rancher2_cluster_alert_rule_test.go
  rancher2/data_source_rancher2_project_alert_group.go
  rancher2/data_source_rancher2_project_alert_group_test.go
  rancher2/data_source_rancher2_project_alert_rule.go
  rancher2/data_source_rancher2_project_alert_rule_test.go
  rancher2/import_rancher2_cluster_alert_group.go
  rancher2/import_rancher2_cluster_alert_rule.go
  rancher2/import_rancher2_project_alert_group.go
  rancher2/import_rancher2_project_alert_rule.go
  rancher2/provider.go
  rancher2/resource_rancher2_cluster_alert_group.go
  rancher2/resource_rancher2_cluster_alert_group_test.go
  rancher2/resource_rancher2_cluster_alert_rule.go
  rancher2/resource_rancher2_cluster_alert_rule_test.go
  rancher2/resource_rancher2_project_alert_group.go
  rancher2/resource_rancher2_project_alert_group_test.go
  rancher2/resource_rancher2_project_alert_rule.go
  rancher2/resource_rancher2_project_alert_rule_test.go
  rancher2/schema_alert_group.go
  rancher2/schema_alert_rule.go
  rancher2/schema_cluster_alert_group.go
  rancher2/schema_cluster_alert_rule.go
  rancher2/schema_project_alert_group.go
  rancher2/schema_project_alert_rule.go
  rancher2/schema_recipient.go
  rancher2/structure_alert_rule.go
  rancher2/structure_alert_rule_test.go
  rancher2/structure_cluster_alert_group.go
  rancher2/structure_cluster_alert_group_test.go
  rancher2/structure_cluster_alert_rule.go
  rancher2/structure_cluster_alert_rule_test.go
  rancher2/structure_project_alert_group.go
  rancher2/structure_project_alert_group_test.go
  rancher2/structure_project_alert_rule.go
  rancher2/structure_project_alert_rule_test.go
  rancher2/structure_recipient.go
  rancher2/structure_recipient_test.go
  website/docs/d/clusterAlertGroup.html.markdown
  website/docs/d/clusterAlertRule.html.markdown
  website/docs/d/projectAlertGroup.html.markdown
  website/docs/d/projectAlertRule.html.markdown
  website/docs/r/clusterAlertGroup.html.markdown
  website/docs/r/clusterAlertRule.html.markdown
  website/docs/r/projectAlertGroup.html.markdown
  website/docs/r/projectAlertRule.html.markdown
  website/rancher2.erb
Labels: size/XXL

#155 Added always_pull_images argument to kube_api for rke clusters
  CHANGELOG.md
  rancher2/schema_cluster_rke_config_services.go
  rancher2/structure_cluster_rke_config_services.go
  rancher2/structure_cluster_rke_config_services_test.go
  website/docs/r/cluster.html.markdown
Labels: documentation, enhancement, size/XS

#158 added missing list item declaration
  website/docs/r/cluster.html.markdown
Labels: documentation, size/XS

#156 Fix password update and resource deletion if not getting active state on creation on rancher2_catalog
  CHANGELOG.md
  rancher2/resource_rancher2_catalog.go
  rancher2/structure_catalog.go
Labels: bug, enhancement, size/XS

#157 Updated always_pull_images argument description on docs
  website/docs/r/cluster.html.markdown
Labels: documentation, size/XS
