Repository rancher/terraform-provider-rancher2, pull requests merged in 2020-02, with the labels that each got.

#239 Added node template support for Opennebula
  rancher2/resource_rancher2_node_template.go
  rancher2/resource_rancher2_node_template_test.go
  rancher2/schema_node_template.go
  rancher2/schema_node_template_opennebula.go
  rancher2/structure_node_template.go
  rancher2/structure_node_template_opennebula.go
  website/docs/r/nodeTemplate.html.markdown
Labels: dependencies, documentation, enhancement, size/XL

#243 Typo in variable name
  rancher2/provider.go
  rancher2/resource_rancher2_bootstrap_test.go
Labels: size/XS

#251 Make kube_config sensitive
  rancher2/schema_cluster.go
  website/docs/r/cluster.html.markdown
Labels: documentation, size/XS

#258 Added plugin optional value none to rke_config argument on rancher2_cluster resource
  CHANGELOG.md
  rancher2/schema_cluster_rke_config_network.go
  website/docs/r/cluster.html.markdown
Labels: documentation, size/XS

#265 Updated private_key_file definition for openstack driver
  CHANGELOG.md
  rancher2/schema_node_template_openstack.go
  website/docs/r/nodeTemplate.html.markdown
Labels: documentation, size/XS
