Repository rancher/terraform-provider-rancher2, pull requests merged in 2020-03, with the labels that each got.

#277 Add PodSecurityPolicyTemplate
  rancher2/data_source_rancher2_pod_security_policy_template.go
  rancher2/data_source_rancher2_pod_security_policy_template_test.go
  rancher2/import_rancher2_pod_security_policy_template.go
  rancher2/provider.go
  rancher2/resource_rancher2_pod_security_policy_template.go
  rancher2/resource_rancher2_pod_security_policy_test.go
  rancher2/schema_pod_security_policy_allowed_csi_drivers.go
  rancher2/schema_pod_security_policy_allowed_flex_volumes.go
  rancher2/schema_pod_security_policy_allowed_host_paths.go
  rancher2/schema_pod_security_policy_fs_group.go
  rancher2/schema_pod_security_policy_host_port_range.go
  rancher2/schema_pod_security_policy_id_range.go
  rancher2/schema_pod_security_policy_proc_mount_type.go
  rancher2/schema_pod_security_policy_run_as_group.go
  rancher2/schema_pod_security_policy_run_as_user.go
  rancher2/schema_pod_security_policy_runtime_class.go
  rancher2/schema_pod_security_policy_se_linux_options.go
  rancher2/schema_pod_security_policy_se_linux_strategy.go
  rancher2/schema_pod_security_policy_supplemental_groups.go
  rancher2/schema_pod_security_policy_template.go
  rancher2/schema_pod_security_policy_volumes.go
  rancher2/structure_pod_security_policy_allowed_csi_drivers.go
  rancher2/structure_pod_security_policy_allowed_csi_drivers_test.go
  rancher2/structure_pod_security_policy_allowed_flex_volumes.go
  rancher2/structure_pod_security_policy_allowed_flex_volumes_test.go
  rancher2/structure_pod_security_policy_allowed_host_paths.go
  rancher2/structure_pod_security_policy_allowed_host_paths_test.go
  rancher2/structure_pod_security_policy_fs_group.go
  rancher2/structure_pod_security_policy_fs_group_test.go
  rancher2/structure_pod_security_policy_host_port_range.go
  rancher2/structure_pod_security_policy_host_port_range_test.go
  rancher2/structure_pod_security_policy_id_ranges.go
  rancher2/structure_pod_security_policy_id_ranges_test.go
  rancher2/structure_pod_security_policy_run_as_group.go
  rancher2/structure_pod_security_policy_run_as_group_test.go
  rancher2/structure_pod_security_policy_run_as_user.go
  rancher2/structure_pod_security_policy_run_as_user_test.go
  rancher2/structure_pod_security_policy_runtime_class_strategy.go
  rancher2/structure_pod_security_policy_runtime_class_strategy_test.go
  rancher2/structure_pod_security_policy_se_linux_options.go
  rancher2/structure_pod_security_policy_se_linux_options_test.go
  rancher2/structure_pod_security_policy_se_linux_strategy.go
  rancher2/structure_pod_security_policy_se_linux_strategy_test.go
  rancher2/structure_pod_security_policy_supplemental_groups.go
  rancher2/structure_pod_security_policy_supplemental_groups_test.go
  rancher2/structure_pod_security_policy_template.go
  rancher2/structure_pod_security_policy_template_test.go
  website/docs/d/podSecurityPolicyTemplate.html.markdown
  website/docs/r/podSecurityPolicyTemplate.html.markdown
Labels: documentation, enhancement, new-data-source, new-resource, size/XXL

#270 Fixed rke_config.cloud_provider.aws_cloud_provider.global argument to avoid false diff
  CHANGELOG.md
  rancher2/schema_cluster_rke_config_cloud_provider_aws.go
  website/docs/r/cluster.html.markdown
Labels: documentation, size/XS

#271 Added custom_target_config argument to cluster and project logging
  CHANGELOG.md
  rancher2/resource_rancher2_cluster_logging.go
  rancher2/resource_rancher2_project_logging.go
  rancher2/schema_cluster_logging.go
  rancher2/schema_logging_custom_target_config.go
  rancher2/schema_project_logging.go
  rancher2/structure_cluster_logging.go
  rancher2/structure_cluster_logging_test.go
  rancher2/structure_logging_custom_target_config.go
  rancher2/structure_logging_custom_target_config_test.go
  rancher2/structure_project_logging.go
  website/docs/r/clusterLogging.html.markdown
  website/docs/r/projectLogging.html.markdown
Labels: documentation, enhancement, size/XL

#276 Added mtu argument to rke_config.network argument on rancher2_cluster resource
  CHANGELOG.md
  go.mod
  go.sum
  rancher2/schema_cluster_rke_config_network.go
  rancher2/structure_cluster_rke_config_network.go
  rancher2/structure_cluster_rke_config_network_test.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_tables.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_test_tables.go
  vendor/github.com/hashicorp/hcl/v2/hclsyntax/expression_vars_gen.go
  vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster.go
  vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster_logging.go
  vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster_logging_spec.go
  vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster_status.go
  vendor/github.com/rancher/types/client/management/v3/zz_generated_network_config.go
  vendor/github.com/rancher/types/client/management/v3/zz_generated_project_logging.go
  vendor/github.com/rancher/types/client/management/v3/zz_generated_project_logging_spec.go
  vendor/github.com/rancher/types/client/management/v3/zz_generated_save_as_template_output.go
  vendor/github.com/rancher/types/client/project/v3/zz_generated_container_port.go
  vendor/github.com/ulikunitz/xz/example.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/modules.txt
  website/docs/r/cluster.html.markdown
Labels: dependencies, documentation, size/XXL

#278 Updated aks_config, eks_config and gke_config arguments to proper update rancher2_cluster resource
  CHANGELOG.md
  rancher2/resource_rancher2_cluster.go
  rancher2/schema_cluster_aks_config.go
  rancher2/schema_cluster_eks_config.go
  rancher2/schema_cluster_gke_config.go
  rancher2/structure_cluster.go
  rancher2/structure_cluster_aks_config.go
  rancher2/structure_cluster_aks_config_test.go
  rancher2/structure_cluster_eks_config.go
  rancher2/structure_cluster_eks_config_test.go
  rancher2/structure_cluster_gke_config.go
  rancher2/structure_cluster_gke_config_test.go
  rancher2/util.go
Labels: bug, size/M

#283 Added wait_monitoring argument to rancher2_cluster_sync
  CHANGELOG.md
  rancher2/resource_rancher2_catalog.go
  rancher2/resource_rancher2_cluster.go
  rancher2/resource_rancher2_cluster_alert_group.go
  rancher2/resource_rancher2_cluster_alert_group_test.go
  rancher2/resource_rancher2_cluster_alert_rule.go
  rancher2/resource_rancher2_cluster_alert_rule_test.go
  rancher2/resource_rancher2_cluster_driver.go
  rancher2/resource_rancher2_cluster_logging.go
  rancher2/resource_rancher2_cluster_role_template_binding.go
  rancher2/resource_rancher2_cluster_sync.go
  rancher2/resource_rancher2_etcd_backup_test.go
  rancher2/resource_rancher2_global_role_binding.go
  rancher2/resource_rancher2_namespace_test.go
  rancher2/resource_rancher2_node_driver.go
  rancher2/resource_rancher2_node_pool.go
  rancher2/resource_rancher2_node_template.go
  rancher2/resource_rancher2_notifier.go
  rancher2/resource_rancher2_notifier_test.go
  rancher2/resource_rancher2_pod_security_policy_template_test.go
  rancher2/resource_rancher2_project.go
  rancher2/resource_rancher2_project_alert_group.go
  rancher2/resource_rancher2_project_alert_group_test.go
  rancher2/resource_rancher2_project_alert_rule.go
  rancher2/resource_rancher2_project_alert_rule_test.go
  rancher2/resource_rancher2_project_logging.go
  rancher2/resource_rancher2_project_role_template_binding.go
  rancher2/resource_rancher2_project_test.go
  rancher2/resource_rancher2_setting.go
  rancher2/resource_rancher2_user.go
  rancher2/schema_cluster_sync.go
  rancher2/util.go
  website/docs/r/clusterSync.html.markdown
Labels: size/L

#282 Added enable_json_parsing argument to cluster and project logging
  rancher2/data_source_rancher2_cluster_logging.go
  rancher2/data_source_rancher2_project_logging.go
  rancher2/schema_cluster_logging.go
  rancher2/schema_project_logging.go
  rancher2/structure_cluster_logging.go
  rancher2/structure_cluster_logging_test.go
  rancher2/structure_project_logging.go
  rancher2/structure_project_logging_test.go
  website/docs/r/clusterLogging.html.markdown
  website/docs/r/projectLogging.html.markdown
Labels: documentation, size/M

#286 Added retries config argument and isRancherActive() function
  CHANGELOG.md
  rancher2/config.go
  rancher2/provider.go
  rancher2/resource_rancher2_cluster_alert_group.go
  rancher2/resource_rancher2_pod_security_policy_template.go
  rancher2/resource_rancher2_pod_security_policy_template_test.go
  rancher2/resource_rancher2_project_alert_group.go
  rancher2/schema_recipient.go
  rancher2/structure_cluster_alert_group_test.go
  rancher2/structure_project_alert_group_test.go
  rancher2/util.go
  website/docs/index.html.markdown
  website/docs/r/clusterAlertGroup.html.markdown
Labels: documentation, size/L
