Repository rancher/terraform-provider-rancher2, pull requests merged in 2020-10, with the labels that each got.

#468 Added new computed ca_cert argument at rancher2_cluster. Fixed `rke_config.monitoring.replicas` argument
  CHANGELOG.md
  docs/data-sources/cluster.md
  docs/resources/cluster.md
  rancher2/resource_rancher2_app.go
  rancher2/schema_cluster.go
  rancher2/schema_cluster_rke_config_monitoring.go
  rancher2/structure_cluster.go
  rancher2/structure_cluster_rke_config_monitoring.go
  scripts/start_k3s.sh
  scripts/start_rancher.sh
Labels: bug, documentation, enhancement

#483 Added dingtal_config and msteams_config arguments at rancher2_notifier resource
  CHANGELOG.md
  docs/data-sources/notifier.md
  docs/resources/notifier.md
  rancher2/0_provider_upgrade_test.go
  rancher2/data_source_rancher2_notifier.go
  rancher2/resource_rancher2_notifier.go
  rancher2/resource_rancher2_notifier_test.go
  rancher2/schema_notifier.go
  rancher2/schema_notifier_dingtalk_config.go
  rancher2/schema_notifier_msteams_config.go
  rancher2/structure_notifier.go
  rancher2/structure_notifier_dingtalk_config.go
  rancher2/structure_notifier_dingtalk_config_test.go
  rancher2/structure_notifier_msteams_config.go
  rancher2/structure_notifier_msteams_config_test.go
  rancher2/structure_notifier_z_test.go
Labels: documentation, enhancement

#484 Fix typo on Registry page
  docs/resources/registry.md
Labels: documentation
