Repository rancher/terraform-provider-rancher2, pull requests merged in 2020-01, with the labels that each got.

#224 Fix template_revisions update on rancher2_cluster_template resource
  CHANGELOG.md
  rancher2/resource_rancher2_cluster_template.go
  rancher2/schema_cluster.go
  rancher2/structure_cluster_template.go
  rancher2/util.go
  website/docs/r/cluster.html.markdown
Labels: documentation, size/S

#221 add windows_prefered_cluster option to cluster schema/structure
  rancher2/schema_cluster.go
  rancher2/structure_cluster.go
  rancher2/structure_cluster_test.go
  website/docs/r/cluster.html.markdown
Labels: documentation, size/XS

#229 Dns policy ingress for RKE
  rancher2/schema_cluster_rke_config_ingress.go
  rancher2/structure_cluster_rke_config_ingress.go
  rancher2/structure_cluster_rke_config_ingress_test.go
  website/docs/r/cluster.html.markdown
Labels: documentation, size/S

#238 Fix rke_config.services.kube_api.policy argument on rancher2_cluster resource
  CHANGELOG.md
  rancher2/schema_cluster_rke_config_services_kube_api.go
  rancher2/structure_cluster_rke_config_services_kube_api.go
  rancher2/structure_cluster_rke_config_services_kube_api_test.go
  rancher2/util.go
  website/docs/r/cluster.html.markdown
Labels: bug, documentation, size/L

#240 Added driver_id argument on rancher2_node_template resource to reference user created rancher2_node_driver
  CHANGELOG.md
  rancher2/resource_rancher2_node_template.go
  rancher2/schema_node_template.go
  rancher2/structure_node_template.go
  website/docs/r/nodeTemplate.html.markdown
Labels: documentation, size/XS

#242 Fix data argument set as sensitive on rancher2_secret resource
  CHANGELOG.md
  rancher2/schema_secret.go
  website/docs/r/secret.html.markdown
Labels: documentation, size/XS
