Repository rancher/terraform-provider-rancher2, pull requests merged in 2020-05, with the labels that each got.

#326 Fix typo in documentation of GKE enable_network_policy_config field
  website/docs/r/cluster.html.markdown
Labels: documentation, size/XS

#331 Fix nodeTemplateStateRefreshFunc function on rancher2_node_template resource
  CHANGELOG.md
  rancher2/resource_rancher2_node_template.go
  rancher2/schema_node_template_amazonec2.go
  rancher2/structure_node_template_amazonec2.go
  website/docs/r/nodeTemplate.html.markdown
Labels: documentation, size/XS

#336 Updated rancher2_app resource to fix local cluster scoped catalogs
  CHANGELOG.md
  rancher2/structure_app.go
  rancher2/structure_app_test.go
  rancher2/util.go
  website/docs/r/app.html.markdown
Labels: bug, documentation, size/M

#338 Added load_balancer_sku argument to azure_cloud_provider configuration
  CHANGELOG.md
  rancher2/schema_cluster_rke_config_cloud_provider_azure.go
  rancher2/structure_cluster_rke_config_cloud_provider_azure.go
  rancher2/structure_cluster_rke_config_cloud_provider_azure_test.go
  website/docs/r/cluster.html.markdown
Labels: documentation, size/S

#346 Update authConfigActiveDirectory.html.markdown
  website/docs/r/authConfigActiveDirectory.html.markdown
Labels: documentation, size/XS
