Repository rancher/terraform-provider-rancher2, pull requests merged in 2020-04, with the labels that each got.

#288 Added fixNodeTempateID to update rancher2_node_template ID
  CHANGELOG.md
  rancher2/config.go
  rancher2/resource_rancher2_node_template.go
  rancher2/structure_node_template.go
  rancher2/util.go
  website/docs/r/nodeTemplate.html.markdown
Labels: documentation, size/M

#301 Fix typo with node template ID fix function.
  CHANGELOG.md
  rancher2/config.go
  rancher2/resource_rancher2_node_template.go
  website/docs/r/nodeTemplate.html.markdown
Labels: documentation, size/XS

#304 Add support for Linode Node Driver
  rancher2/resource_rancher2_cloud_credential.go
  rancher2/resource_rancher2_cloud_credential_test.go
  rancher2/resource_rancher2_node_template.go
  rancher2/resource_rancher2_node_template_test.go
  rancher2/schema_cloud_credential.go
  rancher2/schema_cloud_credential_linode.go
  rancher2/schema_node_template.go
  rancher2/schema_node_template_linode.go
  rancher2/structure_cloud_credential.go
  rancher2/structure_cloud_credential_linode.go
  rancher2/structure_cloud_credential_linode_test.go
  rancher2/structure_cloud_credential_z_test.go
  rancher2/structure_node_template.go
  rancher2/structure_node_template_linode.go
  website/docs/r/cloudCredential.html.markdown
  website/docs/r/nodeTemplate.html.markdown
Labels: documentation, enhancement, size/XL

#306 Fixed rancher timeout on bootstrapping and added monitoring version on rancher2_cluster
  CHANGELOG.md
  rancher2/config.go
  rancher2/provider.go
  rancher2/resource_rancher2_cluster.go
  rancher2/resource_rancher2_project.go
  rancher2/schema_monitoring_input.go
  rancher2/schema_scheduled_cluster_scan.go
  rancher2/structure_monitoring_input.go
  website/docs/index.html.markdown
  website/docs/r/cluster.html.markdown
  website/docs/r/project.html.markdown
Labels: documentation, size/M

#311 Fix project alert group and alert rule datasource and resource documentation
  CHANGELOG.md
  website/rancher2.erb
Labels: documentation, size/XS
