Repository rancher/terraform-provider-rancher2, pull requests merged in 2021-12, with the labels that each got.

#819 Fix rancher2_machine_config_v2 to properly get updated
  CHANGELOG.md
  docs/resources/machine_config_v2.md
  rancher2/schema_machine_config_v2.go
  rancher2/structure_machine_config_v2.go
Labels: bug, [zube]: Review

#658 Add image purchase plan to Azure driver on node_template resource
  docs/resources/node_template.md
  rancher2/schema_node_template_azure.go
  rancher2/structure_node_template_azure.go
Labels: enhancement, dependencies, [zube]: Waiting for Rancher RC

#821 Add support to ECR credential plugin
  CHANGELOG.md
  docs/resources/cluster.md
  rancher2/resource_rancher2_cluster_test.go
  rancher2/schema_cluster_rke_config_private_registries.go
  rancher2/structure_cluster_rke_config_private_registries.go
  rancher2/structure_cluster_rke_config_private_registries_test.go
Labels: enhancement, documentation, [zube]: Review, area/terraform

#830 Fix getClusterKubeconfig function to properly generate kubeconfig for Rancher lower than v2.6.x
  CHANGELOG.md
  docs/resources/cluster.md
  docs/resources/cluster_v2.md
  rancher2/resource_rancher2_cluster.go
Labels: [zube]: Review
