Repository rancher/terraform-provider-rancher2, pull requests merged in 2021-07, with the labels that each got.

#695 New rancher2_node_pool.drain_before_delete argument
  CHANGELOG.md
  docs/resources/node_pool.md
  docs/resources/node_template.md
  rancher2/resource_rancher2_node_pool.go
  rancher2/schema_common.go
  rancher2/schema_node_pool.go
  rancher2/schema_node_template.go
  rancher2/structure_node_pool.go
  rancher2/structure_node_pool_test.go
Labels: [zube]: Review, enhancement

#696 Added new argument rancher2_auth_config_activedirectory.start_tls
  CHANGELOG.md
  docs/resources/auth_config_activedirectory.md
  rancher2/schema_auth_config_activedirectory.go
  rancher2/structure_auth_config_activedirectory.go
  rancher2/structure_auth_config_activedirectory_test.go
Labels: [zube]: Review

#685 Add the kms-key-id parameter to oke config
  docs/resources/cluster.md
  rancher2/schema_cluster_oke_config.go
  rancher2/structure_cluster_oke_config.go
  rancher2/structure_cluster_oke_config_test.go
Labels: dependencies

#707 Added tolerations argument to rke_config
  CHANGELOG.md
  docs/resources/cluster.md
  rancher2/schema_cluster_rke_config_dns.go
  rancher2/schema_cluster_rke_config_ingress.go
  rancher2/schema_cluster_rke_config_monitoring.go
  rancher2/schema_cluster_rke_config_network.go
  rancher2/schema_toleration.go
  rancher2/structure_cluster_rke_config_dns.go
  rancher2/structure_cluster_rke_config_dns_test.go
  rancher2/structure_cluster_rke_config_ingress.go
  rancher2/structure_cluster_rke_config_ingress_test.go
  rancher2/structure_cluster_rke_config_monitoring.go
  rancher2/structure_cluster_rke_config_monitoring_test.go
  rancher2/structure_cluster_rke_config_network.go
  rancher2/structure_cluster_rke_config_network_test.go
  rancher2/structure_toleration.go
  rancher2/structure_toleration_test.go
Labels: [zube]: Review, enhancement

#709 Updated rancher2_cluster resource to properly generate cluster registration token
  CHANGELOG.md
  rancher2/resource_rancher2_cluster.go
  rancher2/schema_cluster.go
  rancher2/structure_cluster.go
Labels: [zube]: Review
