Repository rancher/terraform-provider-rancher2, pull requests merged in 2021-03, with the labels that each got.

#569 Added support to rancher v2.5.6
  CHANGELOG.md
  docs/resources/cluster.md
  go.mod
  go.sum
  rancher2/0_provider_upgrade_test.go
  rancher2/config.go
  rancher2/data_source_rancher2_cluster_test.go
  rancher2/resource_rancher2_app_v2_test.go
  rancher2/resource_rancher2_cluster_test.go
  rancher2/schema_cluster_rke_config_services_etcd.go
  rancher2/structure_cluster_rke_config_services_etcd.go
  rancher2/structure_cluster_rke_config_services_etcd_test.go
  rancher2/structure_etcd_backup_test.go
  scripts/start_rancher.sh
Labels: [zube]: Review, status/working

#570 Fixed issue with hetzner variable naming
  docs/resources/node_template.md
  rancher2/schema_node_template_hetzner.go
  rancher2/structure_node_template_hetzner.go
Labels: [zube]: Review

#614 New rancher2_secret_v2 resource and datausource
  CHANGELOG.md
  GNUmakefile
  docs/data-sources/secret_v2.md
  docs/resources/secret_v2.md
  go.mod
  rancher2/0_provider_upgrade_test.go
  rancher2/config.go
  rancher2/data_source_rancher2_secret_v2.go
  rancher2/data_source_rancher2_secret_v2_test.go
  rancher2/import_rancher2_secret_v2.go
  rancher2/provider.go
  rancher2/resource_rancher2_secret_v2.go
  rancher2/resource_rancher2_secret_v2_test.go
  rancher2/schema_secret_v2.go
  rancher2/structure_secret_v2.go
  rancher2/structure_secret_v2_test.go
  rancher2/util.go
Labels: [zube]: Waiting for RC
