Repository rancher/terraform-provider-rancher2, pull requests merged in 2024-09, with the labels that each got.

#1395 fix: back port for version 5, add check for external rules while updating roleTemplate
  rancher2/resource_rancher2_role_template.go
Labels: kind/bug, version/v5, version/rancher-v2.9

#1396 fix: backport for version 4, add check for external rules while updating roleTemplate
  rancher2/resource_rancher2_role_template.go
Labels: version/rancher-v2.8, version/v4

#1394 Remove extra backticks from node_template.md
  docs/resources/node_template.md
Labels: area/documentation

#1399 Add deprecation notice for pod security policy
  docs/resources/pod_security_policy_template.md
Labels: area/documentation, version/v4

#1400 fix: remove extra return in machine template
  rancher2/resource_rancher2_machine_config_v2.go
Labels: kind/bug, area/rbac

#1401 fix: remove extra return in machine template, back port v5 (#1400)
  rancher2/resource_rancher2_machine_config_v2.go
Labels: version/v5
